### ISSUE TITLE
2 dates, même temps restant

### ISSUE THREAD

**Issue by lyoko17220** [2ec0b4/KaamelottBot#1]
2 dates différentes donnent le même temps restant

https://twitter.com/KaamelottBot/status/1134794230809989120

https://twitter.com/KaamelottBot/status/1134431836900380672

**Comment by 2ec0b4** [comment]
Merci pour ta vigilance ! 😉
C'est corrigé avec ça : https://github.com/2ec0b4/KaamelottBot/commit/52d9c254a5f159007927081dc1d1f2e1176561f8
